#pragma once

#include "game/script/runtime/ScriptControlActions.h"
#include "game/script/runtime/ScriptObjectActions.h"
#include "game/script/runtime/ScriptOrderActions.h"
#include "game/script/runtime/ScriptPlayerActions.h"
#include "game/script/runtime/ScriptPresentationActions.h"

namespace engine::script
{

using ScriptAction = std::variant<ScriptNoOpAction,
                                  ScriptSequentialControlAction,
                                  ScriptSequentialWaitAction,
                                  ScriptSequentialTimedAction,
                                  ScriptSetTeamCustomStateAction,
                                  ScriptSetFlagAction,
                                  ScriptSetCounterAction,
                                  ScriptAdjustCounterAction,
                                  ScriptSetTimerAction,
                                  ScriptAdjustTimerAction,
                                  ScriptSetRandomTimerAction,
                                  ScriptStopTimerAction,
                                  ScriptRestartTimerAction,
                                  ScriptEnableAction,
                                  ScriptDisableAction,
                                  ScriptCallSubroutineAction,
                                   ScriptVictoryAction,
                                   ScriptDefeatAction,
                                   ScriptDebugMessageAction,
                                   ScriptDisplayTextAction,
                                   ScriptDisplayCinematicTextAction,
                                   ScriptMilitaryCaptionAction,
                                   ScriptMovieAction,
                                   ScriptPlayAudioAction,
                                     ScriptMusicAction,
                                     ScriptAmbientAudioAction,
                                  ScriptAudioControlAction,
                                  ScriptTimeControlAction,
                                  ScriptHulkLifetimeOverrideAction,
                                  ScriptScoreAccumulationPolicyAction,
                                  ScriptVisualSpeedAction,
                                  ScriptUiAction,
                                     ScriptCommandBarOverrideAction,
                                     ScriptClientOptionsAction,
                                     ScriptMapPresentationAction,
                                     ScriptObjectPresentationAction,
                                     ScriptForceObjectSelectionAction,
                                     ScriptViewCompatibilityAction,
                                     ScriptCameraAction,
                                     ScriptCameraSlaveAction,
                                     ScriptScreenShakeAction,
                                     ScriptLocalizedCameraShakeAction,
                                     ScriptScreenFadeAction,
                                     ScriptBlackAndWhiteAction,
                                     ScriptMotionBlurAction,
                                     ScriptSkyboxAction,
                                     ScriptTreeSwayAction,
                                     ScriptWeatherAction,
                                     ScriptInfantryLightingAction,
                                   ScriptWaterAction,
                                   ScriptIssueOrderAction,
                                   ScriptFireWeaponFollowingWaypointPathAction,
                                   ScriptBuildTeamAction,
                                   ScriptGuardSupplyCenterAction,
                                   ScriptCreateReinforcementTeamAction,
                                   ScriptRecruitTeamAction,
                                   ScriptUseCommandButtonAction,
                                   ScriptFacingAction,
                                   ScriptAIBehaviorMutationAction,
                                   ScriptAttackPriorityMutationAction,
                                   ScriptStoppingDistanceAction,
                                   ScriptMoveTowardsNearestAction,
                                   ScriptSpecialPowerCountdownAction,
                                   ScriptWarehouseValueAction,
                                   ScriptCaveIndexAction,
                                   ScriptCreateObjectAction,
                                   ScriptDestroyNamedObjectAction,
                                   ScriptLifecycleAction,
                                   ScriptContainmentAction,
                                   ScriptContainmentEnterAction,
                                   ScriptTransferOwnershipAction,
                                   ScriptDamageAction,
                                   ScriptGrantObjectUpgradeAction,
                                   ScriptObjectStateMutationAction,
                                   ScriptGlobalObjectAction,
                                   ScriptBoobyTrapAction,
                                   ScriptToppleDirectionAction,
                                   ScriptModifyObjectTypeListAction,
                                   ScriptSetPlayerCashAction,
                                   ScriptAdjustPlayerCashAction,
                                    ScriptPlayerSellEverythingAction,
                                    ScriptPlayerRepairStructureAction,
                                    ScriptPlayerBuildUpgradeAction,
                                    ScriptPlayerBuildObjectNearTeamAction,
                                    ScriptPlayerBuildSupplyCenterAction,
                                    ScriptSkirmishBuildBuildingAction,
                                    ScriptSkirmishApproachAction,
                                    ScriptSkirmishPerimeterBuildAction,
                                    ScriptSkirmishFireSpecialPowerAtMostCostAction,
                                    ScriptSkirmishAttackNearestValueGroupAction,
                                    ScriptSkirmishMostValuableCommandButtonAction,
                                    ScriptPlayerConstructionAction,
                                   ScriptObjectBuildabilityAction,
                                   ScriptSetPlayerScienceAvailabilityAction,
                                   ScriptSetPlayerRelationshipAction,
                                   ScriptRelationshipOverrideAction,
                                   ScriptGlobalCombatPolicyAction,
                                   ScriptPlayerProgressionAction>;

} // namespace engine::script

