#include "game/object/ai/runtime/ObjectAIShadowBatch.h"

namespace engine::ai
{

[[nodiscard]] ObjectAIShadowBatchColumns ObjectAIShadowBatch::columns() noexcept
{
    return {
        .scheduled = m_scheduled,
        .effectivelyDead = m_effectivelyDead,
        .idleAutoAcquireEnabled = m_idleAutoAcquireEnabled,
        .idleTargetAvailable = m_idleTargetAvailable,
        .idleTargetScanIntervalTicks = m_idleTargetScanIntervalTicks,
        .faceTargetValid = m_faceTargetValid,
        .facingFeedback = m_facingFeedback,
        .canTurnInPlace = m_canTurnInPlace,
        .mobile = m_mobile,
        .moveTargetValid = m_moveTargetValid,
        .hasCurrentLocomotor = m_hasCurrentLocomotor,
        .groundMovement = m_groundMovement,
        .projectile = m_projectile,
        .jetAI = m_jetAI,
        .canBeRepulsed = m_canBeRepulsed,
        .subjectPositions = m_subjectPositions,
        .resolvedMoveTargets = m_resolvedMoveTargets,
        .groupOffsets = m_groupOffsets,
        .wanderOffsets = m_wanderOffsets,
        .groundedDeleteGoals = m_groundedDeleteGoals,
        .ticksPerSecond = m_ticksPerSecond,
        .closestRepulsors = m_closestRepulsors,

        .wanderOffsetXCells = m_wanderOffsetXCells,
        .wanderOffsetYCells = m_wanderOffsetYCells,
        .wanderCellSizeRaw = m_wanderCellSizeRaw,
        .pathfindCellSizeRaw = m_pathfindCellSizeRaw,
        .branchChoice = m_branchChoice,
        .teamProgressTeam = m_teamProgressTeam,
        .teamProgressCurrent = m_teamProgressCurrent,
        .teamProgressRevision = m_teamProgressRevision,
        .pathFeedback = m_pathFeedback,
        .movementFeedback = m_movementFeedback,
        .containmentGoalObjects = m_containmentGoalObjects,
        .containmentFeedback = m_containmentFeedback,
        .disabled = m_disabled,
        .behaviorProfiles = m_behaviorProfiles,
        .behaviorProfileRevisions = m_behaviorProfileRevisions,
        .hackUnpackDurationTicks = m_hackUnpackDurationTicks,
        .hackPackDurationTicks = m_hackPackDurationTicks,
        .hackPayoutPeriodTicks = m_hackPayoutPeriodTicks,
        .hackPayoutAmount = m_hackPayoutAmount,
        .hackExperienceAmount = m_hackExperienceAmount,
        .hackNewestDeferredOrderRevision = m_hackNewestDeferredOrderRevision,
        .constructionComplete = m_constructionComplete,
        .hasAmmo = m_hasAmmo,
        .attackMoodAllowed = m_attackMoodAllowed,
        .attackExitConditionSatisfied = m_attackExitConditionSatisfied,
        .sourceOrderRevisions = m_sourceOrderRevisions,
        .weaponRevisions = m_weaponRevisions,
        .attackGoalObjects = m_attackGoalObjects,
        .attackGoalPositions = m_attackGoalPositions,
        .attackGoalPositionValid = m_attackGoalPositionValid,
        .attackFeedback = m_attackFeedback,
        .dockGoalObjects = m_dockGoalObjects,
        .dockFeedback = m_dockFeedback,
        .insertionGoalObjects = m_insertionGoalObjects,
        .insertionGoalPositions = m_insertionGoalPositions,
        .insertionGoalPositionValid = m_insertionGoalPositionValid,
        .insertionMotionFeedback = m_insertionMotionFeedback,
        .insertionContainmentFeedback = m_insertionContainmentFeedback,
        .insertionOperationFeedback = m_insertionOperationFeedback,
        .enterGuard = m_enterGuard,
        .guardWithoutPursuit = m_guardWithoutPursuit,
        .flyingOnly = m_flyingOnly,
        .tracksAnchor = m_tracksAnchor,
        .contained = m_contained,
        .currentAnchors = m_currentAnchors,
        .initialNemesis = m_initialNemesis,
        .priorityNemesis = m_priorityNemesis,
        .aggressors = m_aggressors,
        .crates = m_crates,
        .cratePositions = m_cratePositions,
        .cratePositionValid = m_cratePositionValid,
        .nearestTunnels = m_nearestTunnels,
        .guardRangeRaw = m_guardRangeRaw,
        .visionRangeRaw = m_visionRangeRaw,
        .initialScanJitter = m_initialScanJitter,
        .guardFeedback = m_guardFeedback,
        .allWeaponsOutOfAmmo = m_allWeaponsOutOfAmmo,
        .allArmyHunt = m_allArmyHunt,
        .useTeamCommonTarget = m_useTeamCommonTarget,
        .targetCollections = m_targetCollections,
        .targetCollectionRevisions = m_targetCollectionRevisions,
        .attackAreas = m_attackAreas,
        .attackAreaRevisions = m_attackAreaRevisions,
        .squadSelections = m_squadSelections,
        .tacticalQueryFeedback = m_tacticalQueryFeedback,
        .tacticalChildFeedback = m_tacticalChildFeedback,
        .opportunityMovementResults = m_opportunityMovementResults,
        .opportunityQueryFeedback = m_opportunityQueryFeedback,
        .opportunityChildFeedback = m_opportunityChildFeedback,
    };
}

[[nodiscard]] AIStateSoAMultiwaveInput ObjectAIShadowBatch::input(AIStateFamilySoAStorage& storage,
                                              uint64_t confirmedTick) noexcept
{
    return input(storage, confirmedTick, m_transitionRequests);
}

[[nodiscard]] AIStateSoAMultiwaveInput ObjectAIShadowBatch::input(
    AIStateFamilySoAStorage& storage,
    uint64_t confirmedTick,
    container::Span<const AIStateSoATransitionRequest> requests) noexcept
{
    return {
        .confirmedTick = confirmedTick,
        .scheduled = m_scheduled,
        .requests = requests,
        .core = {.confirmedTick = confirmedTick,
                 .idleTargetScanIntervalTicks = m_config.idleTargetScanIntervalTicks,
                 .forceIdleBeforeAcquireTicks =
                     m_config.forceIdleBeforeAcquireTicks,
                 .idleTargetScanIntervalTicksBySlot =
                     m_idleTargetScanIntervalTicks,
                 .effectivelyDead = m_effectivelyDead,
                 .idleAutoAcquireEnabled = m_idleAutoAcquireEnabled,
                 .idleTargetAvailable = m_idleTargetAvailable,
                 .results = m_results},
        .facing = {.confirmedTick = confirmedTick,
                   .effectivelyDead = m_effectivelyDead,
                   .faceTargetValid = m_faceTargetValid,
                   .facingFeedback = m_facingFeedback,
                   .canTurnInPlace = m_canTurnInPlace,
                   .results = m_results,
                   .commandBuffers = m_facingCommands},
        .move = {.confirmedTick = confirmedTick,
                 .effectivelyDead = m_effectivelyDead,
                 .mobile = m_mobile,
                 .moveTargetValid = m_moveTargetValid,
                 .groundMovement = m_groundMovement,
                 .subjectPosition = m_subjectPositions,
                 .resolvedMoveTarget = m_resolvedMoveTargets,
                 .ticksPerSecond = m_ticksPerSecond,
                 .pathFeedback = m_pathFeedback,
                 .movementFeedback = m_movementFeedback,
                 .pathRequests = m_pathRequests,
                 .movementCommands = m_movementCommands,
                 .results = m_results},
        .followPath = {.confirmedTick = confirmedTick,
                       .pathfindCellSizeRaw = m_config.followPathCellSizeRaw,
                       .maximumSkippedPoints = m_config.maximumSkippedPathPoints,
                       .effectivelyDead = m_effectivelyDead,
                       .mobile = m_mobile,
                       .groundMovement = m_groundMovement,
                       .projectile = m_projectile,
                       .subjectPosition = m_subjectPositions,
                       .ticksPerSecond = m_ticksPerSecond,
                       .sequences = &m_config.pathSequences,
                       .pathFeedback = m_pathFeedback,
                       .movementFeedback = m_movementFeedback,
                       .pathRequests = m_pathRequests,
                       .movementCommands = m_movementCommands,
                       .results = m_results},
        .waypoint = {.confirmedTick = confirmedTick,
                     .maximumWaypointHops = m_config.maximumWaypointHops,
                     .effectivelyDead = m_effectivelyDead,
                     .mobile = m_mobile,
                     .groundMovement = m_groundMovement,
                     .projectile = m_projectile,
                     .subjectPosition = m_subjectPositions,
                     .groupOffset = m_groupOffsets,
                     .ticksPerSecond = m_ticksPerSecond,
                     .branchChoice = m_branchChoice,
                     .teamProgressTeam = m_teamProgressTeam,
                     .teamProgressCurrent = m_teamProgressCurrent,
                     .teamProgressRevision = m_teamProgressRevision,
                     .waypoints = &m_config.waypointGraph,
                     .pathFeedback = m_pathFeedback,
                     .movementFeedback = m_movementFeedback,
                     .pathRequests = m_pathRequests,
                     .movementCommands = m_movementCommands,
                     .teamProgressRequests = m_teamProgressRequests,
                     .completions = m_waypointCompletions,
                     .results = m_results},
        .moveOutOfWay = {.confirmedTick = confirmedTick,
                          .effectivelyDead = m_effectivelyDead,
                          .mobile = m_mobile,
                          .ticksPerSecond = m_ticksPerSecond,
                          .subjectPosition = m_subjectPositions,
                          .pathFeedback = m_pathFeedback,
                          .movementFeedback = m_movementFeedback,
                          .pathRequests = m_pathRequests,
                          .movementCommands = m_movementCommands,
                         .results = m_results},
        .tighten = {.confirmedTick = confirmedTick,
                    .effectivelyDead = m_effectivelyDead,
                    .mobile = m_mobile,
                    .groundMovement = m_groundMovement,
                    .subjectPosition = m_subjectPositions,
                    .ticksPerSecond = m_ticksPerSecond,
                    .pathFeedback = m_pathFeedback,
                    .movementFeedback = m_movementFeedback,
                    .pathRequests = m_pathRequests,
                    .movementCommands = m_movementCommands,
                    .results = m_results},
        .repulsor = {.confirmedTick = confirmedTick,
                     .effectivelyDead = m_effectivelyDead,
                     .mobile = m_mobile,
                     .canBeRepulsed = m_canBeRepulsed,

                     .subjectPosition = m_subjectPositions,
                     .closestRepulsor = m_closestRepulsors,
                     .wanderOffsetXCells = m_wanderOffsetXCells,
                     .wanderOffsetYCells = m_wanderOffsetYCells,
                     .wanderCellSizeRaw = m_wanderCellSizeRaw,
                     .ticksPerSecond = m_ticksPerSecond,
                     .pathFeedback = m_pathFeedback,
                     .movementFeedback = m_movementFeedback,
                     .pathRequests = m_pathRequests,
                     .movementCommands = m_movementCommands,
                     .results = m_results},
        .wanderPanic = {.confirmedTick = confirmedTick,
                        .repulsorWaitFrames = m_config.repulsorWaitFrames,
                        .effectivelyDead = m_effectivelyDead,
                        .mobile = m_mobile,
                        .groundMovement = m_groundMovement,
                        .projectile = m_projectile,
                        .canBeRepulsed = m_canBeRepulsed,
                        .subjectPosition = m_subjectPositions,
                        .wanderOffset = m_wanderOffsets,
                        .branchChoice = m_branchChoice,
                        .closestRepulsor = m_closestRepulsors,
                        .waypoints = &m_config.waypointGraph,
                        .pathFeedback = m_pathFeedback,
                        .movementFeedback = m_movementFeedback,
                        .pathRequests = m_pathRequests,
                        .movementCommands = m_movementCommands,
                        .completions = m_waypointCompletions,
                        .results = m_results},
        .pickUpCrate = {.confirmedTick = confirmedTick,
                        .effectivelyDead = m_effectivelyDead,
                        .mobile = m_mobile,
                        .moveTargetValid = m_moveTargetValid,
                        .groundMovement = m_groundMovement,
                        .subjectPosition = m_subjectPositions,
                        .resolvedMoveTarget = m_resolvedMoveTargets,
                        .ticksPerSecond = m_ticksPerSecond,
                        .pathFeedback = m_pathFeedback,
                        .movementFeedback = m_movementFeedback,
                        .pathRequests = m_pathRequests,
                        .movementCommands = m_movementCommands,
                        .results = m_results},
        .moveEvacuate = {.confirmedTick = confirmedTick,
                         .effectivelyDead = m_effectivelyDead,
                         .mobile = m_mobile,
                         .moveTargetValid = m_moveTargetValid,
                         .hasCurrentLocomotor = m_hasCurrentLocomotor,
                         .groundMovement = m_groundMovement,
                         .subjectPosition = m_subjectPositions,
                         .resolvedMoveTarget = m_resolvedMoveTargets,
                         .groundedDeleteGoal = m_groundedDeleteGoals,
                         .ticksPerSecond = m_ticksPerSecond,
                         .pathFeedback = m_pathFeedback,
                         .movementFeedback = m_movementFeedback,
                         .pathRequests = m_pathRequests,
                         .movementCommands = m_movementCommands,
                         .commands = m_moveEvacuateCommands,
                         .results = m_results},
        .containment = {.confirmedTick = confirmedTick,
                        .activeStates = storage.payloadStates(),
                        .subjects = storage.subjects(),
                        .goalObjects = m_containmentGoalObjects,
                        .feedback = m_containmentFeedback,
                        .commands = m_containmentCommands,
                        .results = m_results},
        .hackInternet = {.confirmedTick = confirmedTick,
                         .effectivelyDead = m_effectivelyDead,
                         .disabled = m_disabled,
                         .profile = m_behaviorProfiles,
                         .profileRevision = m_behaviorProfileRevisions,
                         .unpackDurationTicks = m_hackUnpackDurationTicks,
                         .packDurationTicks = m_hackPackDurationTicks,
                         .payoutPeriodTicks = m_hackPayoutPeriodTicks,
                         .payoutAmount = m_hackPayoutAmount,
                         .experienceAmount = m_hackExperienceAmount,
                         .newestDeferredOrderRevision = m_hackNewestDeferredOrderRevision,
                         .commands = m_hackCommands,
                         .results = m_results},
        .attack = {.confirmedTick = confirmedTick,
                   .contactExtraDistanceRaw = m_config.attackContactExtraDistanceRaw,
                   .activeStates = storage.payloadStates(),
                   .subjects = storage.subjects(),
                   .effectivelyDead = m_effectivelyDead,
                   .constructionComplete = m_constructionComplete,
                   .hasAmmo = m_hasAmmo,
                   .attackMoodAllowed = m_attackMoodAllowed,
                   .exitConditionSatisfied = m_attackExitConditionSatisfied,
                   .sourceOrderRevisions = m_sourceOrderRevisions,
                   .weaponRevisions = m_weaponRevisions,
                   .goalObjects = m_attackGoalObjects,
                   .goalPositions = m_attackGoalPositions,
                   .hasGoalPositions = m_attackGoalPositionValid,
                   .subjectPositions = m_subjectPositions,
                   .mobile = m_mobile,
                   .groundMovement = m_groundMovement,
                   .projectile = m_projectile,
                   .combatFeedback = m_attackFeedback,
                   .pathFeedback = m_pathFeedback,
                   .movementFeedback = m_movementFeedback,
                   .combatCommands = m_attackCommands,
                   .pathRequests = m_pathRequests,
                   .movementCommands = m_movementCommands,
                   .results = m_results},
        .dock = {.confirmedTick = confirmedTick,
                 .ticksPerSecond = m_config.dockTicksPerSecond,
                 .activeStates = storage.payloadStates(),
                 .subjects = storage.subjects(),
                 .goalObjects = m_dockGoalObjects,
                 .feedback = m_dockFeedback,
                 .requests = m_dockRequests,
                 .results = m_results},
        .insertion = {.confirmedTick = confirmedTick,
                      .activeStates = storage.payloadStates(),
                      .subjects = storage.subjects(),
                      .goalObjects = m_insertionGoalObjects,
                      .goalPositions = m_insertionGoalPositions,
                      .goalPositionValid = m_insertionGoalPositionValid,
                      .parameters = storage.parameters(),
                      .effectivelyDead = m_effectivelyDead,
                      .mobile = m_mobile,
                      .subjectPositions = m_subjectPositions,
                      .pathFeedback = m_pathFeedback,
                      .movementFeedback = m_movementFeedback,
                      .motionFeedback = m_insertionMotionFeedback,
                      .containmentFeedback = m_insertionContainmentFeedback,
                      .operationFeedback = m_insertionOperationFeedback,
                      .motionCommands = m_insertionMotionCommands,

                      .containmentCommands = m_insertionContainmentCommands,
                      .operationCommands = m_insertionOperationCommands,
                      .effectCommands = m_insertionEffectCommands,
                      .pathRequests = m_pathRequests,
                      .movementCommands = m_movementCommands,
                      .results = m_results},
        .guard = {.confirmedTick = confirmedTick,
                  .enemyScanIntervalTicks = m_config.guardEnemyScanIntervalTicks,
                  .returnScanIntervalTicks = m_config.guardReturnScanIntervalTicks,
                  .chaseDurationTicks = m_config.guardChaseDurationTicks,
                  .anchorMoveThresholdRaw = m_config.guardAnchorMoveThresholdRaw,
                  .subjects = storage.subjects(),
                  .sourceOrderRevisions = m_sourceOrderRevisions,
                  .effectivelyDead = m_effectivelyDead,
                  .mobile = m_mobile,
                  .allWeaponsOutOfAmmo = m_allWeaponsOutOfAmmo,
                  .projectile = m_projectile,
                  .jetAI = m_jetAI,
                  .enterGuard = m_enterGuard,
                  .guardWithoutPursuit = m_guardWithoutPursuit,
                  .flyingOnly = m_flyingOnly,
                  .tracksAnchor = m_tracksAnchor,
                  .contained = m_contained,
                  .currentAnchor = m_currentAnchors,
                  .initialNemesis = m_initialNemesis,
                  .priorityNemesis = m_priorityNemesis,
                  .aggressor = m_aggressors,
                  .crate = m_crates,
                  .cratePosition = m_cratePositions,
                  .cratePositionValid = m_cratePositionValid,
                  .nearestTunnel = m_nearestTunnels,
                  .guardRangeRaw = m_guardRangeRaw,
                  .visionRangeRaw = m_visionRangeRaw,
                  .guardAreas = m_attackAreas,
                  .guardAreaRevisions = m_attackAreaRevisions,
                  .initialScanJitter = m_initialScanJitter,
                  .feedback = m_guardFeedback,
                  .tacticalCommands = m_guardTacticalCommands,
                  .interactionCommands = m_guardInteractionCommands,
                  .results = m_results},
        .guardMoveChild = {
            .scheduled = m_guardMoveChildMask,
            .moveTargetValid = m_guardMoveChildTargetValid,
            .resolvedMoveTarget = m_guardMoveChildTargets,
            .results = m_guardMoveChildResults},
        .guardAttackChild = {
            .scheduled = m_guardAttackChildMask,
            .states = m_guardAttackChildStates,
            .goalObjects = m_guardAttackChildTargets,
            .goalPositions = m_guardAttackChildTargetPositions,
            .hasGoalPositions =
                m_guardAttackChildTargetPositionValid,
            .results = m_guardAttackChildResults},
        .tacticalAttack = {.confirmedTick = confirmedTick,
                           .enemyScanIntervalTicks = m_config.tacticalEnemyScanIntervalTicks,
                           .subjects = storage.subjects(),
                           .sourceOrderRevisions = m_sourceOrderRevisions,
                           .effectivelyDead = m_effectivelyDead,
                           .allWeaponsOutOfAmmo = m_allWeaponsOutOfAmmo,
                           .projectile = m_projectile,
                           .allArmyHunt = m_allArmyHunt,
                           .useTeamCommonTarget = m_useTeamCommonTarget,
                           .initialScanJitter = m_initialScanJitter,
                           .targetCollections = m_targetCollections,
                           .targetCollectionRevisions = m_targetCollectionRevisions,
                           .attackAreas = m_attackAreas,
                           .attackAreaRevisions = m_attackAreaRevisions,
                           .squadSelections = m_squadSelections,
                           .queryFeedback = m_tacticalQueryFeedback,
                           .childFeedback = m_tacticalChildFeedback,
                           .queryCommands = m_tacticalQueryCommands,
                           .childCommands = m_tacticalChildCommands,
                           .results = m_results},
        .tacticalAttackChild = {.scheduled = m_tacticalAttackChildMask,
                                .states = m_tacticalAttackChildStates,
                                .goalObjects = m_tacticalAttackChildTargets,
                                .goalPositions = m_tacticalAttackChildTargetPositions,
                                .hasGoalPositions = m_tacticalAttackChildTargetPositionValid,
                                .results = m_tacticalAttackChildResults},
        .tacticalAttackChildFeedback = m_tacticalChildFeedback,
        .opportunityAttackMove = {.confirmedTick = confirmedTick,
                                  .states = storage.payloadStates(),
                                  .subjects = storage.subjects(),
                                  .sourceOrderRevisions = m_sourceOrderRevisions,
                                  .effectivelyDead = m_effectivelyDead,
                                  .mobile = m_mobile,
                                  .groundMovement = m_groundMovement,
                                  .subjectPositions = m_subjectPositions,
                                  .ticksPerSecond = m_ticksPerSecond,
                                  .pathfindCellSizeRaw = m_pathfindCellSizeRaw,
                                  .parameters = storage.parameters(),
                                  .moveToColumns = &storage.moveTo(),
                                  .waypointColumns = &storage.waypointPath(),
                                  .movementResults = m_opportunityMovementResults,
                                  .queryFeedback = m_opportunityQueryFeedback,
                                  .childFeedback = m_opportunityChildFeedback,
                                  .queryCommands = m_opportunityQueryCommands,
                                  .childCommands = m_opportunityChildCommands,
                                  .pathRequests = m_pathRequests,
                                  .movementCommands = m_movementCommands,
                                  .completions = m_waypointCompletions,
                                  .results = m_results},
        .opportunityAttackChild = {.scheduled = m_opportunityAttackChildMask,
                                   .states = m_opportunityAttackChildStates,
                                   .goalObjects = m_opportunityAttackChildTargets,
                                   .goalPositions = m_opportunityAttackChildTargetPositions,
                                   .hasGoalPositions = m_opportunityAttackChildTargetPositionValid,
                                   .results = m_opportunityAttackChildResults},
        .opportunityAttackChildFeedback = m_opportunityChildFeedback,
    };
}

} // namespace engine::ai
