#pragma once

#include "core/container/container_types.h"

#include "core/ecs/registry.h"
#include "game/base/DamageTypes.h"
#include "core/ecs/ObjectId.h"
#include "math/fixed/q32_32.h"

#include <cstdint>
#include "game/object/plan/status/ObjectPoisonedPlanTypes.h"
namespace engine {

class ObjectLifecycle;
struct ObjectDamageRequest;
struct ObjectHealthEvent;

struct ObjectPoisonedRuntime final {
    uint64_t nextDamageTick = 0;
    uint64_t stopTick = 0;
    uint64_t lastDamageTick = UINT64_MAX;
    math::q32_32 damageAmount{};
    ObjectId source = INVALID_OBJECT_ID;
    game::DeathType deathType = game::DeathType::POISONED;
    bool active = false;
};

struct ObjectPoisonedComponent final {
    container::SharedPtr<const game::ObjectPoisonedPlan> plan;
    container::Vector<ObjectPoisonedRuntime> instances;

    [[nodiscard]] bool hasActivePoison() const noexcept;
};

// Damage callbacks and timers are explicit value transitions. No legacy
// DamageModule/UpdateModule pointer survives in a live object.
class ObjectPoisonedSystem final {
public:
    void initializeObject(ecs::registry& registry, ecs::entity entity) const;

    // Called for the exact Body transaction events generated by one request.
    // POISON stores armor-adjusted fixed damage; any accepted HEALING event
    // clears every PoisonedBehavior instance on the victim.
    void onHealthEvent(ecs::registry& registry, ObjectLifecycle& lifecycle,
                       const ObjectHealthEvent& event,
                       uint32_t logicFramesPerSecond) const;

    // Emits at most one periodic hit per instance per confirmed tick. The
    // caller resolves these requests through ObjectSimulation, then invokes
    // finishUpdate so a lethal final pulse can retain the poisoned visual.
    void update(ecs::registry& registry, ObjectLifecycle& lifecycle,
                uint32_t logicFramesPerSecond, uint64_t confirmedTick,
                container::Vector<ObjectDamageRequest>& outDamage) const;
    void finishUpdate(ecs::registry& registry, ObjectLifecycle& lifecycle,
                      uint64_t confirmedTick) const;

private:
    [[nodiscard]] static uint64_t millisecondsToTicks(
        uint32_t milliseconds, uint32_t framesPerSecond) noexcept;
};

} // namespace engine
